name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: docker login --username "Jaisivram" --password-stdin "++*Y.YEk?*^@eR5"
      
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: 
        docker build -t the-diary-image:$(date +%s) .
        docker tag the-diary-image:$(date +%s) jaisivram/the-diary-repo

    - name: docker push 
      run: docker push jaisivram/the-diary-repo
